### ISSUE TITLE
Login form does not show flash message

### ISSUE THREAD

**Issue by jamgar** [stevepolitodesign/rails-authentication-from-scratch#40]
Issue: If I submit incorrect email or password I am not given a message. I am just redirected back the login page.

Location: apps/views/sessions/new.html.erb

I just added a flash message to the form.

```ruby
<!-- app/views/sessions/new.html.erb -->
<%= form_with url: login_path, scope: :user do |form| %>
  <% flash.each do |key,  value| %>
    <%= value %>
  <% end %>
...
<% end %>
```

I would have submitted PR, but not sure how you would like to handle this message.

**Comment by stevepolitodesign** [comment]
@jamgar thank you for pointing this out. We actually have a [shared partial](https://github.com/stevepolitodesign/rails-authentication-from-scratch/blob/main/app/views/shared/_form_errors.html.erb) for rendering form errors. I'm using it on the [users edit form](https://github.com/stevepolitodesign/rails-authentication-from-scratch/blob/c3ce1af4834b8b986b7352e6985941d123275ab7/app/views/users/edit.html.erb#L2), but as you pointed out, I didn't add it to the other forms.

Feel free to make a PR that adds this partial into the forms. We'll just need to make to sure to update both the README and the codebase 👍

**Comment by stevepolitodesign** [comment]
@jamgar I just realized the reason some forms (such as the login form) don't have error messages is that there's no model being passed to the form.

If there's an error while submitting the form, [we render a flash message as seen here](https://github.com/stevepolitodesign/rails-authentication-from-scratch/blob/main/app/controllers/sessions_controller.rb#L17).
