### ISSUE TITLE
Email Validations

### ISSUE THREAD

**Issue by eclectic-coding** [stevepolitodesign/rails-authentication-from-scratch#67]
Steve,
I have been experimenting with ` URI::MailTo::EMAIL_REGEXP ` and it does not appear to be very robust. 

Examples
If you create a user with the email `user` it fails validations as it should.

If you create a user with the email `user@example` it passes validations even though it is not a full email address. 

Might want to consider a more robust solution.

Thanks for the great resource.
Chuck

**Comment by stevepolitodesign** [comment]
@eclectic-coding thank you for taking the time to point this out. Email validation is tricky! I think [the regex that Devise uses ](https://github.com/heartcombo/devise/blob/8593801130f2df94a50863b5db535c272b00efe1/lib/generators/templates/devise.rb#L183-L186) also fails in that case too.

You'll note that the comment reads:

> ...It simply asserts that one (and only one) @ exists in the given string. This is mainly to give user feedback and not to assert e-mail validity.

However, I think we can do a better job of accounting for this by using the correct [input type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) on any form that deals with an email address.

How would you feel about closing out this issue in favor of a new issue focused on using the correct input type?

**Comment by eclectic-coding** [comment]
Sounds like a good approach.

**Comment by stevepolitodesign** [comment]
Closed in favor of #73

**Comment by stevepolitodesign** [comment]
Closed in favor of #73
