### ISSUE TITLE
Amazing Guide

### ISSUE THREAD

**Issue by siba2893** [stevepolitodesign/rails-authentication-from-scratch#84]
Hey this is an amazing guide and I've learned a lot of how authentication systems work. By the way do you think you could potentially adapt a new version of this guide but focused on an API Token Based Application instead of the regular MVC style? You know using Allowlist revocation strategies and stuff like that?

Cause I see how everybody tends to use Devise + Devise-JWT or something else, and it seems like an overkill.

I found this article which seems amazing, maybe you could expand on it?

https://keygen.sh/blog/how-to-implement-api-key-authentication-in-rails-without-devise/

**Comment by stevepolitodesign** [comment]
@siba2893 thank you for the kind words! I've actually written a separate post on [how to build an API in Rails with Authentication](https://stevepolito.design/blog/build-an-api-in-rails-with-authentication/) based off that article.

However, that tutorial was mainly concerned with the server-side aspect of creating authentication. This approach works better for server-side requests to the API, but still works with client-side requests.
