### ISSUE TITLE
Fix `current_user` test helper.

### ISSUE THREAD

**Issue by Tarbetu** [stevepolitodesign/rails-authentication-from-scratch#85]
https://github.com/stevepolitodesign/rails-authentication-from-scratch/blob/9823b3a8682f0132004e0f9a77fb26b197e5be9a/test/test_helper.rb#L17

Hi.

This line seems vague to me. Have you tried to type "elsif" or am I not understanding the purpose of this line? :)

**Comment by stevepolitodesign** [comment]
That's a great catch! Yes, it should be an `elseif`. Thank you for pointing this out.

**Comment by Tarbetu** [comment]
You're welcome! Nice project btw. :)
________________________________

**Comment by stevepolitodesign** [comment]
Closed by #91
